### ISSUE TITLE
[BUG] 1.30 & 1.31 cmd open up with headless (pyinstaller)

### ISSUE THREAD

**Issue by treb00** [microsoft/playwright-python#1778]
- Playwright Version: now 1.29
- Operating System: Windows
- Python version: 3.10
- Browser: tested only chromium

Using playwright with headless mode. When I run the script without builded edition it runs fine in headless mode, no popup, no nothing. However, when I build with pyinstaller and I also use these flags: `--noconsole --excelude-module cmd -F` and using `with sync_playwright() as p:`  in 1.30 and 1.31 cmds popping up. In 1.30 only one empty cmd pops up, in 1.31 multiple windows appear. If I revert back to 1.29 this problem does not occur.

**Comment by mxschmitt** [comment]
to reproduce:
1. create a small python script with Playwright
2. `pythonw.exe test.py`

expected: no window
actual: window shown

to fix it we could add `creationflags=asyncio.subprocess.CREATE_NO_WINDOW` inside `_transport.py` but that regresses other stuff.

**Comment by SK-415** [comment]
Hi, since this issue has been fixed in playwright v1.31.1, will playwright-python also release a fix patch?

**Comment by mxschmitt** [comment]
1.31.1 will have less/no windows on windows with normal setup. The pythonw issue still remains.

**Comment by fabrree** [comment]
Is there any fix available for the cmd window pop ups? 
I am on version 1.31.2. 
Does the new version resolve this?

**Comment by erma0** [comment]
> Is there any fix available for the cmd window pop ups? I am on version 1.31.2. Does the new version resolve this?

Not yet, but you can edit  the `create_subprocess_exec` function for file `playwright/_impl/_transport.py` on your local machine, just add one arg like this:
`creationflags=134217728 if sys.platform == "win32" else 0,`
Then using `pyinstaller -w` will work fine

**Comment by fabrree** [comment]
> > Is there any fix available for the cmd window pop ups? I am on version 1.31.2. Does the new version resolve this?
> 
> Not yet, but you can edit the `create_subprocess_exec` function for file `playwright/_impl/_transport.py` on your local machine, just add one arg like this: `creationflags=134217728 if sys.platform == "win32" else 0,` Then using `pyinstaller -w` will work fine


Thank you, this works fantasic! 
Does this number 134217728 have any influence or is it just random?

**Comment by erma0** [comment]
> > > Is there any fix available for the cmd window pop ups? I am on version 1.31.2. Does the new version resolve this?
> > 
> > 
> > Not yet, but you can edit the `create_subprocess_exec` function for file `playwright/_impl/_transport.py` on your local machine, just add one arg like this: `creationflags=134217728 if sys.platform == "win32" else 0,` Then using `pyinstaller -w` will work fine
> 
> Thank you, this works fantasic! Does this number 134217728 have any influence or is it just random?

This is the constant `subprocess.CREATE_NO_WINDOW`

**Comment by mxschmitt** [comment]
We should probably do the following:

```python
            startupinfo = None
            if sys.platform == "win32":
                startupinfo = subprocess.STARTUPINFO()
                startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
                startupinfo.wShowWindow = subprocess.SW_HIDE

            self._proc = await asyncio.create_subprocess_exec(
                str(self._driver_executable),
                "run-driver",
                stdin=asyncio.subprocess.PIPE,
                stdout=asyncio.subprocess.PIPE,
                stderr=_get_stderr_fileno(),
                limit=32768,
                env=env,
                startupinfo=startupinfo,
            )
```

**Comment by farshadz1997** [comment]
> We should probably do the following:
> 
> ```python
>             startupinfo = None
>             if sys.platform == "win32":
>                 startupinfo = subprocess.STARTUPINFO()
>                 startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
>                 startupinfo.wShowWindow = subprocess.SW_HIDE
> 
>             self._proc = await asyncio.create_subprocess_exec(
>                 str(self._driver_executable),
>                 "run-driver",
>                 stdin=asyncio.subprocess.PIPE,
>                 stdout=asyncio.subprocess.PIPE,
>                 stderr=_get_stderr_fileno(),
>                 limit=32768,
>                 env=env,
>                 startupinfo=startupinfo,
>             )
> ```

Hello

thank you for this snippet, it would be awesome if you add this in the following versions of Playwright.
